// TODO(hbt) NEXT review this file -- some info copied / broken down into other files e.g monetization. less of vision doc and more brainstorming
== Deliberate practice hub

I want a site where there is a step by step roadmap on how to achieve expertise on a particular subject. 
The content is organized, resources are available and it is centered around deliberate practice research.


This means the site must have:

- feature -- example
- a clear goal per topic -- increase software productivity / increase software development effectiveness  
- a clear set of metrics  -- reduce dev time relative to new software project complexity 
- list of strategies to attain expertise (from beginner to expert) -- learn to code / getting a software job / soft skills / AI
- why a particular strategy is a good investment and the expected return -- learning to code = information economy and ability to manipulate that information, extend your mind and automate the world around 
- metrics to measure your progress in said task and why those metrics are relevant and whether you should increase/decrease them -- touch typing = speed, how frequently you look for keys etc.
- clear feedback loop - 
- list of existing resources/tools related to achieving strategy -- e.g flash cards software to learn apis, touch typing software to practice on the keyboard etc.
- mentorship -- forums where people can ask those who achieved it 
- mental representations -- thinking of vim as a language and finding common patterns
- tagged resources


== incentives

- self improvement 
- potential monetization (mentorships, jobs, sponsored content)
- building reputation in community + gamification & achievements (e.g stackoverflow?)
- ability to fork + contribute easily + see other people's work


== Monetization

moved to 38


== roadmap

39

== design brainstorming

. collaborative / wiki style? / curated
. watch/star resources -- same as github and be notified to ease maintenance
. add people as admin and give them rights
. voting system for pull requests.
. since the focus is on software, consider working around github, maybe gists?


== site names ideas

. masteryjourney.com *
. expertjourney.com
. deliberatepractice.io
. dphub.io

== example

touch type

. why? - time spent searching for keys or looking at the keyboard. interrupts flow of thought. slows you down. 
. metrics -
. resources - touch type tools
. tags - keyboard (view related - e.g mouseless browsing, ide keyboard shortcuts, terminal vim etc.)


