== Deliberate practice hub

I want a site where there is a step by step roadmap on how to achieve expertise on a particular subject. 
The content is organized, resources are available and it is centered around deliberate practice research.


This means the site must have:

- feature -- example
- a clear goal per topic -- increase software productivity / increase software development effectiveness  
- a clear set of metrics  -- reduce dev time relative to new software project complexity 
- list of strategies to attain expertise (from beginner to expert) -- learn to code / getting a software job / soft skills / AI
- why a particular strategy is a good investment and the expected return -- learning to code = information economy and ability to manipulate that information, extend your mind and automate the world around 
- metrics to measure your progress in said task and why those metrics are relevant and whether you should increase/decrease them -- touch typing = speed, how frequently you look for keys etc.
- list of existing resources/tools related to achieving strategy -- e.g flash cards software to learn apis, touch typing software to practice on the keyboard etc.
- mentorship -- forums where people can ask those who achieved it 


== incentives

- self improvement 
- potential monetization (mentorships, jobs, sponsored content)
- building reputation in community + gamification & achievements (e.g stackoverflow?)
- 


== Monetization

- the most obvious is sponsored tools / advertisement
- related businesses promoted (aka content marketing)
- mentorship/mentee for people who achieved a particular strategy or are working on getting there. / could translate to job board / consulting
- a new type of resume / gamification aspect where skills are completed and measured + displayed as public profile
- applied to companies / official projects -- step by step on how to master a product and measured completion + resources (e.g complex products like mouseless with a great learning where a deliberate practice hub api is provided)


== roadmap

. determine mvp and data structures (mostly content at this point)
. focus on software development and build high value strategies/content
. extend to other areas of interests (e.g nutrition, intelligence, health quantification)
. api idea for gamification + deliberate practice -- knowledge tree / skills tree type thing . maybe even with unlocks, achievements etc. 

