== Gist of experiment 
A quick experiment centered around this idea is to build an awk equivalent utility tool. 

It would be available via the cli, you can transform strings like linux pipe commands and using multiple functions or straight up using the php wrapper. 

You should also be able to add new functions, publish them and make them available in the cloud. 

Limiting data type to strings only for now. 

There are already tools to provide faas. see if those can be reused + wrapped up and built upon. This way, I can focus on the wrapper instead of services + infrastructure. 

== flow

. add function that inserts block of text between 2 identified blocks  -- regex example http://www.perlmonks.org/?node_id=7633
. publish version on cloud
. write fh wrapper for cloud calls and multi strings functions
. cat file | fh "function_call('bl_start', 'bl_end', 'insert_text').trim()"

== tools 

. http://swagger.io/
. https://webtask.io/cli#


== experimenting with webtask

wrote 2 functions with webtask. problem is limitations in the language, environment etc. 
I need full flexibility and that means firing docker containers without whatever is inside of them.

// TODO(hbt) NEXT add ideas to mindmap
fh should handle the CPU/RAM needs by monitoring usage. If the function is using 100% CPU, move it to a higher instance and increase the price. Same with RAM. 
Or maybe offer option for user to run on lowest or highest speed in the future. 


== more flexible tools to investigate



. aws lambda https://aws.amazon.com/lambda/
. aws ec2 container service https://aws.amazon.com/ecs/
. https://github.com/serverless/serverless most popular 
. Kubernetes https://en.wikipedia.org/wiki/Kubernetes#History https://kubernetes.io/ https://platform9.com/blog/compare-kubernetes-vs-ecs/
. https://github.com/bigcompany/hook.io related to microcule
. https://github.com/Stackvana/microcule functinos and processes
. https://github.com/alexellis/faas package processes as functions
. https://github.com/funktionio built on top of Kubernetes (but many languages?)
. https://github.com/iron-io/functions functions only (but many languages?)
. https://github.com/fission/fission functions only (nodeJS and python only) doesnt look well maintained (outdated docs and such)


also check the topics tags for more
. lambda
. functions
. serverless
. functions-as-a-service

Conclusion:

Using aws lambda + ecs should cover all needs. ecs supports docker and orchestration like kubernetes + you get all the aws services. 
lamba despite its limitations can be used for smaller functions.

In addition, there is plenty of docs, support, community, tools etc. compared to other services. 
It's easier to start with that than gamble on smaller startups and such
