
== doc objective

. clarify vision + structure of systems
. organize thought


== end goal

. list of functions callable over the cloud abstracting complex functionality into simple + accessible calls and executable over any platform


== function registry

. list of functions. similar to dockerhub or github. create functionshub
. easy to add new ones, fork and collaborate
. google index equivalent of functions
. can run registry over cloud or local
. community owned

=== metrics

. nb functions

=== flaws/concerns

. dealing with contributions, custom functions and forking
. no technical advantage  - google search algo vs google index

=== leap forwards

. github/dockerhub like hosting for OSS
. accessibility, ease of use, ease of mashups (no install, piping/mashing up)

=== design

. database + api
. tools to manipulate registry
. avoid the need for private/custom registries but design for it. goal is to create a hub not isolated nodes
. push integration with other functionshub services instead of modularity. 

=== function definition

- REST api definition 

reuse swagger or raml or other similar tool. Make it easier to port existing definitions of APIs to function registry. 
People already use annotations to specify their APIs, generate docs etc.

each function is a REST api with all best practices applied.

- reliable intercommunication for mashups (json versioning, protocol buffers)

will be using JSON communication over REST for now. However, something like protocol buffers must be implemented. 
Key advantage is dealing with versioning, api changes and ease of mashups. Example: api definition changes (e.g name change) and its dependencies could be auto-updated instead of frozen to one version. Or, optimization is made and could result in reduced billing.

- integration with platform (matchers, logging, issue reporting etc.)

matchers are essential to detect input + data types and promote functions. Discoverability. 
Example: a function that operates on youtube content would have a matcher for youtube urls but wouldn't appear when a dailymotion URL is inserted.
a function for downloading videos would appear for both


- name

camelCase only? free names? both?


- aliases

same as descriptions. domain dependent. indexOf, stripos means nothing to mainstream. findCharacterPosition might.

- description

names, aliases and description are the main ways of searching and understanding what a function does. 
followed by examples (the inline tests)

- namespace

to allow custom names and deal with conflict between functions with same names/aliases
also to organize functions 

- tags

not too sure about that. maybe something similar to github topics? 
Find better ways to enhance discoverability

- data type

kind of like a class name. a function expecting a data type as input, expects a specific JSON definition / structure. 
users can then convert between data types if needed. Example: YouTubeVideo DailyMotionVideo which will have different JSON structures since it is written by different people. Maybe different field names and such. Machine learning will come into play to create auto converters. 
Once we have a converter, then the functions from dailymotion can be used by youtube.
This allows further transformation of inputs and increases matchers

It should be strong typed but might result in converters nightmare. Not sure how to avoid that and still have complex custom structures. 

- matchers

list of boolean assertions to run against input to see if this function can handle it. 

Allow for second degree matchers.
Example: a function that only handles files but a url is submitted. thanks to converters url to file (i.e download), it can now handle it. 

- user notes 

in addition to description, for users to find them later

- inline testing

input/output assertions

- manifest versioning 

a clear manifest with paths to upgrade. Example: if we introduce matchers in future versions, we can auto-update functions in the registry.

. versioning

REST api version

. pricing / billing

custom pricing


=== cloud hosting integrations function definition

. issue tracking, reliability, status
. stackoverflow like Q&A for support on each function and its version -- reuse api or buy stackexchange subdomain?
. logging - all inputs/ouputs, exec time and resources consumed (memory, bandwidth)
. analytics - replicate or differ to api providers functionality



=== workflows

tools can be developed to accelerate workflow and make it easier to fork, develop functions. 
A lot of these features should be part of functions hosting.
Key goal here is to define a function for the registry

- adding a new function

. fork registry repo
. create folder for data type and namespace
. write function definition
. write function and embed into docker
. write tests

- alternative way

. write inline function in your language in a file
. submit file url 
. system analyzes function and creates fucntion definition skeleton. Annotations can control definition.
. system auto-fills with sane defaults regarding namespace and other function definition details


== function hosting

. built on of registry
. hosting + billing per use
. offers caching, storage and other range of APIs to make it easier to run/write/debug/analyze functions
. offers hidden optimizations



== UI

. built on top of registry and hosting
. multiple UIs (cli, language wrappers, web, mobile, api, voice (smart assistant)) 
. mash functions together with ease (inv nimbletext and complex piping)


== UX

. must be mainstream friendly without sacrificing power users. powerful and easy
. machine learning - learn from usage and enhance UX. Example: functions often used together and recommendations, how people build functions and improvements in UI, smart assistant

