:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== 2-core-ideas-31



== Accelerate the software cycle

The site will:

- analyze every step of the software development cycle. 
- list current tools and alternatives 
- historical view of tools/solutions and problem identification (root problem)
- future tools to 10x improvements or eliminate/automate 

== Deliberate practice resources for software engineers

Site will:

- list resources and strategies to enhance as a software engineer
- attempt to structure content based on a path



Since most of it is content + writing, I can do the work here and publish properly when ready.