:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== 3-related-ideas-26




This project has been on my mind for over a year. I started it then stopped because I lost track and other stuff got in the way. 


I still don't have a clear objective as to what I want out of it. So, here some rambling.


== deliberate practice

I've been fascinating by intelligence augmentation, acquisition of expertise, deliberate practice and getting better at stuff effectively.

However, the moment you step out of something like sports or music, that mechanical repetition building muscle memory and get into cognitive stuff, it becomes a different ball game.


There is plenty of writing online on how to deliberate practice programming and it is mostly mumbo jumbo bullshit that boils down to:

- write a lot of code
- read a lot of code
- learn this programming paradigm, it will change your life
- get a slower computer, it will force you to write optimal shit
- cut your left arm, it will force you to type slower and think before you type. 


That kind of advice. Where it sounds like it makes sense until you realize:
 
- you have no clue which piece of code to read
- how do you read code? what are you supposed to look for? do you pick projects based on what interests you? based on complexity?


It's often compared to writing. 

Anyway, I decided to get serious about it and look into it about a year ago and gathered a shit ton of litterature on acquisition of expertise in different domains (writing, programming, mathematics) and had several ideas on how to organize the content etc. 

Then, I kinda got overwhelmed in the chaos of information, another project came up, got distracted by life stuff and didn't revisit the project. 

It has been lingering in my head box for months though but there was so much stuff that need to be reorganized and read again and thought about, that I didn't bother. 

That's definitely a big thing I learned about projects. Make sure you have your next task broken down into a small doable chunk. A chunk no longer than 20m that you can get done and is relevant. Otherwise, you're not gonna come back to it unless you really have to.


== Journey from A to Z

What I want is a mixture of two things:

. exploring deliberate practice out of self interest to become better. Improving myself as a software engineer generally means being able to build quality stuff quicker, accomplish my goals/vision faster relative to problem complexity. 
. the second thing, I want what I should have had when I started. Kinda of like a guide from A to Z on how to learn programming and progressively get better. I already have several ideas on how to build that guide without repeating existing information out there. 


This is the key part. I often feel like there is no value to my writing/work because it feels like a rehash. However, before digging deeply into a subject and doing all that research, finding a "rehash" would have been extremely valuable. There is value in rehashing / repetitive work / spinning. 

But, some topics have been talked to so vaguely and so repetitively that I would frustrate myself even writing about them.


== the future of software

In addition to the cw project, I wrote a lot on the future of software, automation, intelligence etc. 

A lot of it was kinda original until I googled the subject matter, found the right keywords and realized there are entire institutes with people a lot smarter than me who dedicated their lives to those topics. The subject of superintelligence was one of them. The future institute or whatever the name of the place where Nick Bostrom worked at.

== The development cycle and accelerating 

Finally, the last one is how to accelerate automation, how to accelerate the software development cycle. 

This is somewhat related to deliberate practice but goes beyond individual self improvement. Kinda like crowd-intelligence / technological-innovation approach to intelligence augmentation


So, tons of this writing is on my little journal for my prying eyes only (and the cloud watchers) but I don't want to simply do a copy / paste and share it. 
I want to restructure it (or attempt to turn rambling into structured thoughts), clear it up for myself. It would help me decide on upcoming projects and how to design them.



---

Those are the big 3 themes around this project. Not sure yet of the best structure but right now, the goal is to go through the material quickly, familiarize myself with it again then build an outline. 


They are highly related though. Maybe one project, increase software productivity/effectiveness or something along those lines. Approached both from an individual perspective and software.