:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== basic-scripting-and-automation-72



## Iteration 3


Let's automate those repetitive steps from earlier.



A few solutions:

. Use a keyboard macro program like xmacro to record the pressed keys and mouse clicks
.. You have to get the timing right. If there is any problem like the video taking too long or the site changing, it will fail. 
.. When it fails, you have no idea why until you examine each step. 
. use a robot software like "selenium" to control complex states like waiting, status codes etc.
.. gets more complicated and requires knowledge in selenium
.. still has to be maintained every time the site is updated 
. Search and use tools on github
.. too complicated for majority of users to find right keywords, domain language and identify the right tool
.. too complicated to install the tool on their computer and test it
.. too complicated to diagnose why the tool stopped working and how to fix it


After using the https://www.onlinevideoconverter.com/video-converter site, you realize they have a quota + hard limit on the size of the video that *they never mention anywhere... just fails silently*. 
So, option 1 & 2 are out and you're left with option 3. 





Let's get this done!


### download the youtube video

Found youtube-dl https://github.com/rg3/youtube-dl

Install it 

```
pip install youtube-dl
```

Try it 

`youtube-dl https://www.youtube.com/watch?v=vt9UZo32KMk`

We have the video file. Awesome.

Let's stop for a second and look what a user needed to know to achieve this:

. github, github repositories, open-source software and what it is expected from you as a user
. basic understanding command line
. pip is a package manager for python and python is a programming language amongst many


OK. This assumes we did not run into any issues:

- installing python/pip and upgrading libraries or dealing with incompatible platforms
- youtube-dl working out of the gate. No cache issues, no need to upgrade, no permissions problems etc.


### Convert the video to audio


We can go back to hunting for software interfaces with GUI that force you to do everything manually 

*OR*

We magically figure out that a piece of software with the most obscure of names already exists. 


```
sudo apt-get install avconv
avconv -i a1.m4b -vn a1.mp3
```

OK. Let's stop again. Here is what the user needed to know:

- sound can be extracted from a video using software. 
- although there is tons of software with GUIs, you really want the one with command line because that's the only one you can automate
- when you go online and look for "command line video sound extraction" you keep seeing "ffmpeg" but you can't install it
- instead you can install avconv which comes with your distribution, is a fork of ffmpeg but you can install ffmpeg from another repository source or the latest distribution
- you can copy/paste the avconv parameters you saw on stackoverflow or spend time reading the help and the tons of features/flag/arguments/parameters to figure out how to do what you want to do.


### put the audio file on my phone

Remember what this whole thing was about again? Yeah, don't lose track and waste time!!

OK. So I have the sound file on my computer and want it on my phone. Easy Peasy. 

. Plug the phone into my computer and transfer using usb/mtp/whatever
.. Sucks to have to plug the phone every time you want to transfer
. Look into blutooth
.. pain in the ass to pair the devices, too slow, still manual
. Look into installing an FTP/SSH app on the phone and automatically start it. 
.. too clunky
.. service doesn't start automatically
. Look into uploading the file to google drive / dropbox and use the app to automatically sync
.. downloading is fine but upload speed sucks (Thanks Canadian telecoms)



Again, since the google drive site UI is useless for automation, the API involves too much programming we find a utility called "drive" on github


```
# Install drive
mkdir -p /goroot && \
    curl https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
ENV GOROOT /goroot
ENV GOPATH /gopath
ENV PATH $GOROOT/bin:$GOPATH/bin:$PATH
go get -u github.com/odeke-em/drive/cmd/drive
```

I'm not even gonna bother listing the things the user needs to know at this point.


- drive is installed
- we get a token/credential to the google drive account
- we push the file to google drive
- file is automatically synced on the phone



### Putting it all together.

A quick bash script to link things together.

. It accepts a url 
. downloads it
. extracts the audio
. uploads the audio


### still handling one video at the time

that's easy. Put a bunch of urls into a file. use xargs or a loop to go through them. 
You don't get parallel processing since you don't have the computational resources though.

.video-converter
[source,bash]
----

sudo pip install --upgrade --quiet youtube-dl
youtube-dl --rm-cache-dir
youtube-dl -v --no-playlist $1

for i in *.mkv; do avconv -i $i -vn $i.mp3;done
for i in *.webm; do avconv -i $i -vn $i.mp3;done
for i in *.mp4; do avconv -i $i -vn $i.mp3;done

drive push --no-prompt *.mp3
srm -rf *
----


## Iteration 4

OK. We have a script to download/convert/upload anything. 


Issues:

- youtube-dl breaks and require an upgrade because it uses a crawler. you need to ugprade when youtube site changes its code
- download bandwidth and speed are limited on local computer
- ffmpeg consumes a whole CPU and also takes time
- upload process takes even more time since it is a fraction of the download speed.


Let's improve it further and see the cost + ease of improvements. 



### Internet speed issues

Run it on the cloud. 


- find cheap vm  where bandwidth is not an issue e.g linode
- install the software (repeat steps above) and replicate state of your local machine
- copy the bash script we created earlier
- use SCP to upload the file listing the youtube urls
- run it over SSH


```
scp -r "links.txt" hbt@hbtlabs.com:links.txt
ssh hbt@hbtlabs.com video-converter.sh 
```
