link:index[Home]

= bringing mouseless to the average user (brainstorming)
:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments



## bringing mouseless to the average user

I've been thinking about building a mouseless chrome extension that I could sell for years. 
Since 2012, when discussing vrome, I thought about monetizing it somehow. 

I think, it is pretty clear at this point that this would be useless. 

First:

- the best chrome extension is cvim. In terms of functionality but also something I'd use, it is not the most popular though. 

The most popular is vimium. Mainly because it has a minimal feature set and is ideal for beginners. 

The problem I have right now is any work to monetize the extension would consist of bringing mouseless to the average user. 
The average user who:

- doesnt want to spent any time customizing stuff
- doesnt want to spend time learning 
- expects things to work **at their level** out of the gate


There are a few advantages to be gained by bringing to the average users but not enough to justify the amount of work + risk . 

Keep in mind, if I do this, there would be a big risk of people not showing up or being satisfied with the free versions etc. 


The key technical advantages I'd gain are:

- better hinttags and other user defined stuff -- that's assuming the majority of people are not passive and it's worth having hinttags for sites that I dont visit
- better bug detection / software quality?

I cant think of what there is to gain really. 


Bringing it to the majority of users would be an education app. After they reach their education, they might be tempted to switch to the free version. 

It's not like chromium-vim is super buggy.

Maybe that would be the tool instead. An education/gamification app or book or whatever. 


Learn chromium-vim, pentadactyl etc. and would have documentation, gifs, community scripts, examples, wikis etc. 

Not sure where the monetization would be or even if there would be traffic but most importantly, what's in it for me?


I think I just need a break from this project for awhile. I had some ideas about yubnub like features, cli for the web and whatnot. 


