:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== conclusion-7



Definitely not worth monetizing. The white flash crowd is loud but they are not that numerous. 
Although, I do get 50 unique visitors a week now as of Jan 2017. Very few follow through and download the binaries (for ubuntu).
Shoulda tracked the windows ones.





I guess some are intimated or lost by the repository page and expect something more friendly. 


The primary goal of recruiting collaborators and advanced users was reached though.

- Jonathan forked and built on top of my fix and did a great job fixing the colors [https://github.com/imatimba/darker-chromium](https://github.com/imatimba/darker-chromium)
- he will be providing weekly stable windows binaries
- I'm deep enough in the white flash community to know when something better comes along. Like the jollo.org guy who got notified because he put his work out there. 

Too small a market and too much work (marketing, support, updates) for little pay despite all the voiced frustrations.
Maybe I could have known this from the google search results, product forums views, google trends and such. I was counting on people being as frustrated as I am with the bug to justify using a fork. Few are.


Still worth fixing for myself and still worth sharing since other people built on top the fix and improved the solution.


Putting the project on hold for now.
