:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== features-ideas-list-37




== guideline

. clear ROI on metrics
. prioritized by highest ROI
. more like experiments than features. should be easy to remove/revert/disable/toggle/deploy for target audience only etc.



== features (reorg/review)

. rename strategies to skills?
. star / follow particular strategy and be notified of new tools / resources
. track mastered skills - if already mastered, mark it as "mastered" 
. define your path by starring strategies and marking them as done. Compare paths with others and fork when needed
. ipaas with tools to measure progress and display
. display public profile of mastered skills, wip and tbd
. display this list of enhancements and get people to upvote the ones they want implemented
