:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== investigate similar ideas




I'd like to investigate similar ideas before even thinking about the technical design.

Maybe it can be built on top of Zapier or an existing platform instead of building everything from scratch. 

Although a lot of what I want is the equivalent of distributed functions. 


== alternatives

// TODO(hbt) NEXT quick review of services if they can be built upon
. Zapier https://zapier.com/
. mulesoft https://www.mulesoft.com/
. workato https://www.workato.com/
. built.io https://www.built.io/
. automate.io https://automate.io/
. https://www.integromat.com/en/
. https://bip.io/
. https://fr8.co/
. https://www.cloudpipes.com/
. https://cloudwork.com/
. https://www.elastic.io/
. yahoo pipes
. https://skyvia.com/data-integration/
. http://proces.io/
. https://azuqua.com/
. https://flow.microsoft.com/en-us/
. https://cloud.google.com/dataflow/


== link aggregators 

// TODO(hbt) NEXT find ipaas saas and other acronyms
. ipaas - integration platform as a service. https://www.google.ca/search?q=ipaas&oq=ipaas&aqs=chrome..69i57j0l5.1093j0j4&sourceid=chrome&ie=UTF-8
. https://www.getapp.com/it-management-software/a/zapier/alternatives
. http://alternativeto.net/software/zapier/?license=opensource
. http://alternativeto.net/software/zapier/?license=commercial
. http://alternativeto.net/software/zapier/?license=free
. http://alternativeto.net/software/zapier/
. http://apievangelist.com/2013/02/10/bringing-etl-to-the-masses-with-apis/


== comparison + review tool

. https://comparisons.financesonline.com/zapier-vs-workato


== differentiators

. focus on open source tools, easy access, publishing + monetization instead of hooking to company xyz API
. focus on developers workflow (writing, publishing, testing, monetizing) -- plenty of room since most companies dont cater to developers, especially OSS
. focus on customer workflow (easy creation, billing, managing etc.) -- no major differentiators there and should be done later
. easy site / app building  -- late

== faas

. https://webtask.io/
. https://github.com/serverless/serverless
. good faas review 2016 https://martinfowler.com/articles/serverless.html

== api management

. http://blog.cloud-elements.com/convergence-api-management-ipaas-ready

== conclusion

. ipaas etl serverless computing (function as a service faas) were the keywords I was looking for and describe the application domain
. multiple services exist but no where near what I want. Need to further review them if they can be built upon. 
. focusing on end user apps is most likely the wrong way to go. It is necessary though but maybe easier to connect to an aggregator instead. Focus should be on OSS and software inacessible to most users (due to complex install, hidden features etc.)
. it should be as easy as a google input but gets things done.

// TODO(hbt) NEXT update vision doc about wolframalpha + restify/dockerfy/saas/faas/paas git repos
// TODO(hbt) NEXT inv wolframalpha new apis
// TODO(hbt) NEXT think about atomic approach to end goal: apify, restify, dockerize, faas, wolfram etc.
// TODO(hbt) NEXT read https://www.mulesoft.com/resources/cloudhub/what-is-ipaas-gartner-provides-reference-model