:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== lessons-learned-43



I don't know if I should have jumped to the prototype right away. 

Doing the market analysis + research helped me find niche communities like r/learnprogramming, freecodecamp, read several posts on how beginners are struggling and find tons of resources for beginners.

If I jumped directly to prototype, I would have written a lot of text that is repetitive and it would be yet another resource online amongst many with some original content but mostly redundant stuff.

I do think however spending too much time on brainstorming features + monetization was kind of a waste. However, I did not feel comfortable pushing the project without that brainstorming. It felt like working on a deadend or small task that was going nowhere. I needed a long term vision to fuel the short term goals. 
