:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== me and the keyboard. a love story.



## a bit of history - mouseless


I've been accumulating keyboard shortcuts for years. 
It peaked around my time using editors and IDE and my obsession of removing the mouse. 

=== 2009
Around 2009, I started using vim heavily in a mod and started looking into adding keyboard shortcut to phpmyadmin .

=== 2010
Instead I found out about vimium, pretty sure it was on hackernews. I then jumped on it, looked into the code and [forked it adding many features](https://github.com/hbt/vimium) 

=== 2011 / 2012
Afterwards, I found out about vrome, but the code quality felt much better. Jumped in, [forked it, added a bunch of features.](https://github.com/hbt/vrome)

I contacted the author jinzhu and he gave me admin access.
He did a release behind my back, it had tons of experimental features and some bugs. Wasnt meant for release. 

He then proceeded to rewrite the whole extension in coffeescript with no discussion. It kinda felt like all my work in JS was discarded and I stopped contributing.
In reality though, a lot of my work was translated to coffeescript and he did a good job keeping the best parts and giving me credit as a retired author a few years later.
Better communication would have helped us both.


=== 2013

Around 2013, I got really tired of the white flash bug combined with the lack of stylesheet injections. 
Also, the vrome extension didnt allow me the level of customization I needed. 

I switched to firefox, picked pentadactyl and used that for years. The same firefox version until a small update which created too much work to justify updating the browser. 


=== 2016

In 2016, I had a browser that was clunky, didnt work very often, would crash with timeouts and connection reset, some pages werent supported or looked buggy, it was overall slow and tedious. I could not update the damn thing without risk breaking pentadactyl or doing more work to fix it again. 

Firefox market share and development tools were on the decline.
The decision to switch to chrome was made but first the white flash bug had to be fixed. 

Fixed the white flash bug, fixed my vrome fork to work with latest google chrome, looked into alternatives and found cvim aka chromium-vim. 


I proceeded to customize chromium and make it work in tandem with vrome. By the end, I no longer opened firefox and had no use for pentadactyl. 

But now, I had 2 extensions doing pretty much the same thing and some weird bugs. Forked cvim, merged my work from vrome into it and disabled vrome. 

This is where I'm at now. 

Firefox + pentadactyl are gone. Vrome is gone. I have the browser I want and it works properly. 