:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments

link:index[Home]

== My history with this bug



## what is the white flash?

The chromium white flash is this fucking annoying bug that has existed forever. 
Basically, a white flash appears whenever you change tabs, new tab, click a link, open a window, begin to relax. [explained here](http://youtu.be/HfJ_EwSTevI)
Instead of browsing while enjoying ads ridden pages and lag, you have to experience the equivalent of getting flash banged in call of duty every few seconds.


## personal history of frustration

Like every problem in life, it's only worth solving when it really pisses you off. My frustration with white flash has been building over the years slowly. 

- 2007, began changing the background colors of site to relax my eyes in firefox. 
- 2008, began experiencing migraine and eye strain. It was a combination of poor sleeping habits, poor lighting and working during the evening
- 2009, none of the sleeping issues were addressed but used global stylesheets 
- 2010, browsing in black and white and switching to chrome on linux. The white flash story begins.
- 2011-2013, white flashes appear but it's not as bad because we have custom stylesheet injection reducing the effect. 
- 2013, chromium team [removes custom stylesheets](https://codereview.chromium.org/64843004) and I switch to firefox. 
- 2013-2016, using firefox and not experiencing any issues with white flashes except when I have to test something on chrome.
- 2016, firefox is increasingly a dead end and chromium is becoming the default browser. Must switch to chrome and fix the white flash.

