:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== not-too-sure-about-strings-prototype-idea-57




I dont think I'm gonna push the idea too far. Some aspects of it are common across all functions and it's worth building those components. 

Strings prototyping offers an oversimplication. 

However, I have no use for most of those functions at the moment and would rather not spend time writing wrappers / documentation for them. i.e the grunt work aspect of building them up once the all components exist.


The video mp3 processing is something i use daily and offers even more complex problems such as storage etc. -- view 56