:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== putting-a-video-on-my-phone-71




## end goal

 "I want to listen to podcast/lectures from youtube while I run errands."


## Iteration 1

Easy peasy. 

. Download the youtube app
. Play the video

// TODO(hbt) add image youtube player

### Issues

. Internet is not cheap nor fast in Canada.
.. Find a youtube offline app 
. Advertisements in the youtube app are distracting/annoying 
.. Find another app like "youtube red" to skip/remove advertisements
. Often don't need the video since I can't watch it, only need the audio. Turning off the phone, pauses the video.
.. Download the video and extract the audio
. Nothing can be done with the phone while youtube app is on.
.. Use a regular media player to play downloaded content
. Sometimes content is from other sources too e.g vimeo or soundcloud
.. download video from more than source.

## Iteration 2

You can search the google play store for a multitude of youtube apps that do what you want. Trying them one at the time and perhaps even buying some.
Normally at this point, people accept a compromise. I can do this but not that, too bad, "c'est la vie". They get frustrated and move on. 
 
 
For the small minority of people technologically savvy enough, they will do a google search.
A google search is only fruitful if you know the domain. Otherwise, you are inundated by sleazy websites promising what you want and under delivering.

Examples:

. https://www.google.ca/search?ei=c5r3WYK1H6u4jwS1-bjYAg&q=extract+audio+from+youtube&oq=extract+audio+from+&gs_l=psy-ab.3.0.0i20i263k1j0l9.1921.11631.0.12449.32.25.7.0.0.0.208.2813.5j15j2.23.0....0...1.1.64.psy-ab..2.30.2940.6..35i39k1j0i67k1j0i131k1j0i131i46k1j46i131k1.116.yTlo1smHOko
. https://www.google.ca/search?ei=PJr3WePSNaXijwTllqSIDg&q=download+youtube+videos&oq=download+youtube&gs_l=psy-ab.3.0.0i131k1j0i20i263k1j0l8.49991.51720.0.53560.16.12.0.0.0.0.275.1573.0j7j2.9.0....0...1.1.64.psy-ab..7.9.1564...35i39k1.0.dbEocb1DBOI


You can actually find really great tools e.g https://www.onlinevideoconverter.com/video-converter

Problem solved!

// TODO(hbt) add screenshot https://www.onlinevideoconverter.com/video-converter

Here are the steps the user has to perform each time they want a video on their phone:
 
. copy the youtube url
. go to https://www.onlinevideoconverter.com/video-converter
. paste the youtube url
. click "Start"
. wait
. Click "Download mp3"

If you have multiple videos or a playlist, repeat this process for each one. 


### Issues

. This is tedious and repetitive (especially if you want multiple videos)
.. Automate the download to audio conversion


## A quick recap

At this point, we lost the vast majority of users. At each iteration, the solutions get better but accessibility to said solution gets worse.

To recap, here is what we are asking from users:

### notice a problem and be proactive. 

 "I want to play youtube videos but it is not economical to do it on my cellphone plan. Do I give up on what I want? blame government sanctioned oligopolies and rant about rich greedy telecom owners?  or do I look for an alternative solution?"

### understand the domain and basic concepts.
 
 "Youtube is an app. Advertisements are not ingrained in the video but are separate. A video is a file and can be broken download into images and sound. The data does not reside in youtube but on a site/server. Can I use something other than an app to access that data? Can I use a browser? Another app?"
 
### find alternative solutions and evaluate them

  "If youtube is an app and not just a magic icon that was installed on my phone when I bought it. Can I go to the playstore, find other apps, install them, evaluate them, breakdown their features as independent systems, compare them and find a better fit?"
  "If the youtube app on my phone is just an interface, can I do a google search with the right keywords, find another tool to access the video, download it ... ?"
  
### Identify the manual steps involved in the solution 

  "I have to do all these steps, maybe I don't have to. Maybe there is a better way. Maybe I can do something about improving this solution"




People are not stupid but generally ignorant about the domain and its complexity. They often build their own model of reality and belief system and use them to operate around the world. 

This doesn't account for personality and emotions; people who get angry/frustrated easily, people who give up at the first sign of a challenge, people who are "afraid to break it" because no one is around to fix it etc.


All of these people with their different backgrounds and understanding of the world force you to fragment your product. They each represent a significant enough market segment and yet you cannot design something to be a perfect fit for all of them.

That is the frustration of product development. You have to pick your market segment, build a solution for each one of them. 
The language used by the software has to fit how your segment models reality.


More people using your product means it has to please the lowest common denominator. Needs of the many ...



## What if

What if you could create an interface that anyone could wrap their heads around?
A simple pattern anyone can understand.


`Input -> Transformation -> Output`


What if the interface was just plain english and it adjusted automatically to your understanding of the world by learning from people like you? No matter how small your customer segment, *someone alreayd tried to do what you want to do*. 

Why are repeating the same work individually over and over?


What if you could easily create, share and consume automated systems (software)? 

What if independent systems could communicate with each other with no prior agreement?

What if you could easily scale your computational resources based on your needs?


This is what we are going to build


## Iteration 3


Let's automate those repetitive steps from earlier.



A few solutions:

. Use a keyboard macro program like xmacro to record the pressed keys and mouse clicks
.. You have to get the timing right. If there is any problem like the video taking too long or the site changing, it will fail. 
.. When it fails, you have no idea why until you examine each step. 
. use a robot software like "selenium" to control complex states like waiting, status codes etc.
.. gets more complicated and requires knowledge in selenium
.. still has to be maintained every time the site is updated 
. Search and use tools on github
.. too complicated for majority of users to find right keywords, domain language and identify the right tool
.. too complicated to install the tool on their computer and test it
.. too complicated to diagnose why the tool stopped working and how to fix it


After using the https://www.onlinevideoconverter.com/video-converter site, you realize they have a quota + hard limit on the size of the video that *they never mention anywhere... just fails silently*. 
So, option 1 & 2 are out and you're left with option 3. 





Let's get this done!


### download the youtube video

Found youtube-dl https://github.com/rg3/youtube-dl

Install it 

```
pip install youtube-dl
```

Try it 

`youtube-dl https://www.youtube.com/watch?v=vt9UZo32KMk`

We have the video file. Awesome.

Let's stop for a second and look what a user needed to know to achieve this:

. github, github repositories, open-source software and what it is expected from you as a user
. basic understanding command line
. pip is a package manager for python and python is a programming language amongst many


OK. This assumes we did not run into any issues:

- installing python/pip and upgrading libraries or dealing with incompatible platforms
- youtube-dl working out of the gate. No cache issues, no need to upgrade, no permissions problems etc.


### Convert the video to audio


We can go back to hunting for software interfaces with GUI that force you to do everything manually 

*OR*

We magically figure out that a piece of software with the most obscure of names already exists. 


```
sudo apt-get install avconv
avconv -i a1.m4b -vn a1.mp3
```

OK. Let's stop again. Here is what the user needed to know:

- sound can be extracted from a video using software. 
- although there is tons of software with GUIs, you really want the one with command line because that's the only one you can automate
- when you go online and look for "command line video sound extraction" you keep seeing "ffmpeg" but you can't install it
- instead you can install avconv which comes with your distribution, is a fork of ffmpeg but you can install ffmpeg from another repository source or the latest distribution
- you can copy/paste the avconv parameters you saw on stackoverflow or spend time reading the help and the tons of features/flag/arguments/parameters to figure out how to do what you want to do.


### put the audio file on my phone

Remember what this whole thing was about again? Yeah, don't lose track and waste time!!

OK. So I have the sound file on my computer and want it on my phone. Easy Peasy. 

. Plug the phone into my computer and transfer using usb/mtp/whatever
.. Sucks to have to plug the phone every time you want to transfer
. Look into blutooth
.. pain in the ass to pair the devices, too slow, still manual
. Look into installing an FTP/SSH app on the phone and automatically start it. 
.. too clunky
.. service doesn't start automatically
. Look into uploading the file to google drive / dropbox and use the app to automatically sync
.. downloading is fine but upload speed sucks



Again, since the google drive site UI is useless for automation, the API involves too much programming we find a utility called "drive" on github


```
# Install drive
mkdir -p /goroot && \
    curl https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
ENV GOROOT /goroot
ENV GOPATH /gopath
ENV PATH $GOROOT/bin:$GOPATH/bin:$PATH
go get -u github.com/odeke-em/drive/cmd/drive
```

I'm not even gonna bother listing the things the user needs to know at this point.


- drive is installed
- we get a token/credential to the google drive account
- we push the file to google drive
- file is automatically synced on the phone



### Putting it all together.

A quick bash script to link things together.

. It accepts a url 
. downloads it
. extracts the audio
. uploads the audio


### still handling one video at the time

that's easy. Put a bunch of urls into a file. use xargs or a loop to go through them. 
You don't get parallel processing since you don't have the computational resources though.

```
for i in *.mkv; do avconv -i $i -vn $i.mp3;done
```


## Iteration 4

OK. We have a script to download/convert/upload anything. 


Issues:

- youtube-dl breaks and require an upgrade because it uses a crawler. you need to ugprade when youtube site changes its code
- download bandwidth and speed are limited. It takes time to download 
- ffmpeg consumes a whole CPU and also takes time
- upload process takes even more time since it is a fraction of the download speed.


Let's improve it further and see the cost + ease of improvements. 





### Internet speed issues

Run it on the cloud. 


- find cheap vm  where bandwidth is not an issue e.g linode
- install the software (repeat step above) and replicate state of your local machine
- copy the bash script we created earlier
- use SCP to upload the file listing the youtube urls
- run it over SSH


```
scp -r "links.txt" hbt@linode.com:links.txt
ssh hbt@mylinode.com video-converter.sh 
```

### CPU issues



## Iteration 5


Issues:

- maintaining the state of the remote machine is annoying. e.g upgrading youtube-dl and making sure things don't break
- cannot have dedicated vm for just a script. installing other software could break the script by unintentionally upgrading other libraries
- ffmpeg consumes a whole CPU and also takes time


### Use containers instead of only VMs. 

Dockerfy the whole project and its dependencies. Deploy locally or on any vm easy and use easily.

Dockerfile
[source,Dockerfile]
----

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl git python g++ build-essential python-pip ffmpeg

# install youtube-dl
RUN pip install youtube-dl

# Install drive
RUN mkdir -p /goroot && \
    curl https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
ENV GOROOT /goroot
ENV GOPATH /gopath
ENV PATH $GOROOT/bin:$GOPATH/bin:$PATH
RUN go get -u github.com/odeke-em/drive/cmd/drive

# install node using nvm
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
# to use source
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# // TODO(hbt) ENHANCE pass node version as env variable to not repeat it
RUN source /root/.nvm/nvm.sh && nvm install 8.6.0 && nvm use 8.6.0 && npm update -g
RUN ln -s /root/.nvm/versions/node/v8.6.0/bin/node /usr/bin/node
RUN ln -s /root/.nvm/versions/node/v8.6.0/bin/npm /usr/bin/npm

RUN apt-get install -y psmisc

RUN npm install mocha -g

RUN mkdir /project
WORKDIR /project

COPY *.json /project/
RUN npm install 
---



