:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== roadmap-33




== functions registry

. map strings functions and provide as lambda or over ecs
. registry supports dataType search / discovery 
. limit to simple data types before introducing complex data structures (google protocol buffers)
. registry contains
.. function definition data types (in and out), parameters, function name, aliases, namespaces
.. docs description, examples
.. source code link, lambda/docker/ecs link, rest link
.. function version
.. nb times runs / issues reported (flagged not working) / comments / Q&A / nb users -- logging each time user runs a function
.. price, execution time, resources consumed

== php/ruby wrapper

. can make chained commands

== cli wrapper

. similar ui to hook.io  - using unix pipes
. supports chained commands 

== UI

. jsplumbkit or similar
. ui reverse engineered from functions registry

== user can create own functions

. faasify - aws lambda / serverless
. dockerfy complex services e.g youtube-dl

== replicate youtube-dl workflow

. fh client on local computer or dropbox?



