:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');

</script>
++++

link:index[Home2]

== Sleazy marketing



== marketing chromium white flash fix

since the windows binaries have been produced and the github repo has gained some work. I want to get more contributors for several reasons:

- have the built maintained for me on other platforms
- get better solutions implemented 
- be notified when people get something better


This can be measured by the number of downloads, traffic, feedback, visits, gihub stars etc. 

What I dont want:

- answer dummy questions from users. Most of them unlikely to contribute anything. 
- do any extra work on the fork


## marketing strategy

- focus on google links of popular sites and contact authors to notify them of latest fix
- do reverse search and contact the sites that made the top links popular


## approach

- github pages instead of README + focused on end-users to get them to download and try it right away
- FAQ for common questions 


## steps

- find keywords
- extract list of links + authors
  - use google searches
  - check for refs to chrome bugs about white flash
  - reverse the searches 
- fix github pages, faq, readme
- contact authors and followups
- review traffic, gh stars and other metrics



## keywords

```
google chrome white flash fix
chromium white flash fix
https://www.google.ca/search?q=google+chrome+white+flash+fix&oq=google+chrome+white+flash+fix&aqs=chrome..69i57j69i60l2j69i64.3983j0j4&sourceid=chrome&ie=UTF-8
https://www.google.ca/search?q=prevent+white+flash+between+pages&sa=X&ved=0ahUKEwiv3onL2pnRAhWqx4MKHfJzCeoQ1QIIWCgA
https://www.google.ca/search?q=white+screen+flashes+between+page+loads&sa=X&ved=0ahUKEwiQvLTX2pnRAhVH3IMKHYlyAwEQ1QIIZygH
https://www.google.ca/search?q=prevent+white+flash+between+pages+chrome&sa=X&ved=0ahUKEwiQvLTX2pnRAhVH3IMKHYlyAwEQ1QIIZigG
https://www.google.ca/search?q=html+white+flash+between+pages&sa=X&ved=0ahUKEwiQvLTX2pnRAhVH3IMKHYlyAwEQ1QIIZSgF
https://www.google.ca/search?q=page+blinks+when+loading&sa=X&ved=0ahUKEwiQvLTX2pnRAhVH3IMKHYlyAwEQ1QIIZCgE
https://www.google.ca/search?q=annoying-white-flash-during-page-transitions-in-google-chrome&sa=X&ved=0ahUKEwiQvLTX2pnRAhVH3IMKHYlyAwEQ1QIIYygD
https://www.google.ca/search?q=white+flash+between+page+loads&sa=X&ved=0ahUKEwiQvLTX2pnRAhVH3IMKHYlyAwEQ1QIIYigC
```

use paste to open in all tabs

## list of links authors
  
```  
http://jollo.org/LNT/public/chrome-white-flash.html 
 aehtyb@gmail.com

https://productforums.google.com/forum/#!topic/chrome/OhHr9gqj06k
https://productforums.google.com/forum/#!msg/chrome/xyeVe5URIRw/D7BeDF7-cDQJ
https://productforums.google.com/forum/#!topic/chrome/Rmd8IyUjG68
https://productforums.google.com/forum/#!topic/chrome/QRT_BgCVtGQ
https://productforums.google.com/forum/#!topic/chrome/M_gtcHph_ZQ
https://productforums.google.com/forum/#!topic/chromebook-central/hT6fC84e9x0
https://productforums.google.com/forum/?hl=ja#!topic/chrome/Rmd8IyUjG68;context-place=forum/chrome
https://productforums.google.com/forum/#!msg/chrome/MmE6g_72NfQ/gERNaAC9AQAJ
https://productforums.google.com/forum/#!topic/chrome/VJ8BIbS_Z4g

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/9bQW9ss9b6I
http://stackoverflow.com/questions/36159420/google-chrome-override-white-blank-page-when-loading-new-tabs/36248224
http://superuser.com/questions/717343/how-can-i-make-chromes-white-flash-when-a-new-tab-is-opened-be-black
https://twitter.com/search?q=%23endtheflashbang&src=typd
https://www.reddit.com/r/chrome/comments/55wttj/chrome_white_flashflashbang/
https://twitter.com/search?q=chrome%20white%20flash&src=typd
https://www.reddit.com/r/chrome/comments/4qdf08/how_is_the_white_flash_when_clicking_a_link/
https://www.reddit.com/r/chrome/search?q=white+flash&restrict_sr=on&sort=relevance&t=all
https://www.reddit.com/r/chrome/comments/2sldn6/help_is_there_a_fix_for_the_white_flash_between/
https://www.youtube.com/watch?v=uNfxhKI4SkU
https://www.youtube.com/results?search_query=chrome+white+flash
http://stackoverflow.com/questions/16243105/google-chrome-override-white-blank-page-between-webpage-loads
http://stackexchange.com/search?q=chrome+white+flash
http://www.position-relative.com/2011/the-good-and-bad/botheration/the-chrome-white-flash/  
https://forum.userstyles.org/discussion/47558/white-flash-chrome
http://stackoverflow.com/questions/31875773/why-only-chrome-is-white-flashing-between-pages
https://linustechtips.com/main/topic/108565-how-to-remove-the-irritating-white-screen-when-loading-the-next-page/
http://superuser.com/questions/580228/prevent-white-screen-before-loading-page-in-chromium
http://superuser.com/questions/717343/how-can-i-make-chromes-white-flash-when-a-new-tab-is-opened-be-black?lq=1
http://stackoverflow.com/questions/31221548/how-to-dim-chrome-loading-screen-between-page-loads-to-black-out-white-flash
```


## find most valuable / influencial links

where influencial is:

- appears high in google results
- has multiple views + replies + followups
- uses social media and can trend (reddit,twitter)


## feedback + followups

- contacted people on reddit - several users
- updated superuser questions
- contacted a few people via productforums g+ because the google groups does not allow replies
- tweeted to a few people 

## traffic metrics

- https://www.reddit.com/message/inbox/
- https://twitter.com/
- http://superuser.com/questions/717343/how-can-i-make-chromes-white-flash-when-a-new-tab-is-opened-be-black/1161482#1161482


## other ideas

consider registering to chrome google groups productforums + emailing whenever a mention is made about white flash
you can get daily summaries and use a gmail filter for flagging. 

Why? because I can't comment on old threads and people have their emails hidden. I could google them and find their email, but that's a lot of work. 


## feedback

- People need a direct link for binaries - i.e a github pages instead of README
- People don't read README (duh) and expects a direct download + install ala google chrome
- People keep posting about google sync and other stuff not working (despite clearly explained in README)
- Only works for very frustrated people experiencing the bug. Some people claim to be frustrated but are not willing to actually put a bit of effort.

Out of all the marketing, tweets, reddit, stackoverflow etc. Only one highly influencial user turned out to be worth it and drove a lot of new traffic. 


