:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== solving-the-high-context-switching-and-development-workflow-58




From 55, context switching was the most annoying and time consuming aspect. 

If I can streamline that, I will reduce the dev of a function.


== ideal workflow

. create empty folder
. create file in language x with functions in them
. document functions inputs(main input)/outputs/assertions etc. with annotations in the file
. use fh local test to:
.. build the docker file
.. build your functions definitions
.. run your tests - if missing deps are found, auto-correct
. fh remote deploy
.. deploys image on functionhub 
.. version it
.. run tests

