:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== the deliberate practice guide - outline




Software deliberate practice guide. A-Z guide covering the journey of self improvement and increasing effectiveness. 
Ha. So fucking corny. 


outline in link:28.php
link:the-deliberate-practice-guide-28[the deliberate practice guide]


It's difficult to organize the content, write it and research it; at the same time. 


The way I envision this project is a site tracking resources related to deliberate practice and increasing software productivity, an attempt should be made to provide a step by step guide for self improvement.

I need to search for similar sites first.

