:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== thinking about vision and end goal




Ideally, I want the white flash bug fixed in google chrome so I dont have to maintain a fork in the first place. 

However, since that's not going to happen anytime soon and I have no interest in digging my heels into the codebase. Here. we. are.


There are 2 aspects to maintaining the fork:

. stable binaries to be produced using the latest stable code
. dealing with any merge conflicts as we update the code


Since the changes are minimal, merge conflicts shouldn't be a problem. 

It would be great to somewhat automate the browser updating part. Problem is, it's a giant pain in the ass and is time consuming to build for my platform, let alone other platforms. Dependency hell is waiting to happen, I just know it. 

Maybe have a VM and produce the binaries there. 

There is some demand online for a fix, maybe it can be made economically viable so the costs for renting a VM + keeping up the latest version is spread amongst collaborators and customers.

