:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== vcsh-setup-13



== my setup 

We have 4 environments minimium. 

- Desktop - local/personal environment
- laptop - still personal but slightly different than desktop
- servers - personal servers
- work servers - consulting/public servers


This means 4 repositories. 


Each repository has 2 branches.

- common - anything in common between repositories
- private - the stuff that only pertains to that environment


All repositories are checked in on the desktop. One private branch and 3 common branches.

The other environments only have access to their respective repositories. 

If something needs to be shared, it is shared on the common branch.



[source,bash]
----
vcsh init dotfiles
vcsh init hbtlabs_dotfiles 

# hide all files from status unless I specifically add them
# downside: if a new file is added to a tracked directory, it will not appear in status. 
vcsh  dotfiles_hbtlabs config --local status.showUntrackedFiles no

vcsh enter dotfiles_hbtlabs

# regular git commands
git s
----


Refs: this guide https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/ was of great help