:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== vision-34



== Deliberate practice hub

I want a site where there is a step by step roadmap on how to achieve expertise on a particular subject. 
The content is organized, resources are available and it is centered around deliberate practice research.


This means the site must have:

- feature -- example
- a clear goal per topic -- increase software productivity / increase software development effectiveness  
- a clear set of metrics  -- reduce dev time relative to new software project complexity 
- list of strategies to attain expertise (from beginner to expert) -- learn to code / getting a software job / soft skills / AI
- why a particular strategy is a good investment and the expected return -- learning to code = information economy and ability to manipulate that information, extend your mind and automate the world around 
- metrics to measure your progress in said task and why those metrics are relevant and whether you should increase/decrease them -- touch typing = speed, how frequently you look for keys etc.
- clear feedback loop - 
- list of existing resources/tools related to achieving strategy -- e.g flash cards software to learn apis, touch typing software to practice on the keyboard etc.
- mentorship -- forums where people can ask those who achieved it 


== incentives

- self improvement 
- potential monetization (mentorships, jobs, sponsored content)
- building reputation in community + gamification & achievements (e.g stackoverflow?)
- ability to fork + contribute easily + see other people's work


== Monetization

- the most obvious is sponsored tools / advertisement
- related businesses promoted (aka content marketing)
- mentorship/mentee for people who achieved a particular strategy or are working on getting there. / could translate to job board / consulting
- a new type of resume / gamification aspect where skills are completed and measured + displayed as public profile
- applied to companies / official projects -- step by step on how to master a product and measured completion + resources (e.g complex products like mouseless with a great learning where a deliberate practice hub api is provided)


== roadmap

. determine mvp and data structures (mostly content at this point)
. focus on software development and build high value strategies/content
. extend to other areas of interests (e.g nutrition, intelligence, health quantification)
. api idea for gamification + deliberate practice -- knowledge tree / skills tree type thing . maybe even with unlocks, achievements etc. 


== design brainstorming

. collaborative / wiki style? / curated
. watch/star resources -- same as github and be notified to ease maintenance
. add people as admin and give them rights
. voting system for pull requests.
. since the focus is on software, consider working around github, maybe gists?


== sites

. masteryjourney.com
. expertjourney.com
. deliberatepractice.io
. dbhub.io


// TODO(hbt) NEXT integrates notes from todos -- acc-dev e.g mental representation and mentorships (peak book)