:uri-asciidoctor: http://asciidoctor.org
:icons: font
:source-highlighter: pygments
:nofooter:

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-90513711-1', 'auto');
  ga('send', 'pageview');
</script>
++++

link:index[Home]

== writing and self censorship



== writing quality

There is something therapeutic about writing. It helps clear the mind and structure your thoughts. 

However, it's okay to just write and ramble. Not every post has to be polished and held to extreme standards. Why not?
Because you wouldn't bother writing in the first place. 

There is no interest in even polishing older posts to be more structured or readable. 

Generally, the goal is to clear your mind about a project/decision/problem. Most of the posts are works in progress. 

== watch that tone

Frustration and anger are part of software development. You cannot spend your days digging into other people's minds and attempting
to understand what were they thinking implementing it this way or designing that way without going a little mad. 

Also, shit doen't always work as expected and it can be frustrating. So, cursing comes easy with this type of writing.


Lastly, self censorship. One reason to not write under your own name is the deluge of professional online victims waiting to make you as miserable as they are. 
Hopefully, they won't be reading in the first place ;-)

