# Site settings
title: hbtlabs
email: "hassenbentanfous@gmail.com"
description: ""
baseurl: "http://hbt.github.io/projects-log"
url: "http://hbt.github.io/projects-log"
future: true

# Build settings
markdown: kramdown
permalink: pretty
